apiVersion: apps/v1
kind: Deployment
metadata:
  name: acesteps-service
  labels:
    app: acesteps-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acesteps-service
  template:
    metadata:
      labels:
        app: acesteps-service
    spec:
      containers:
      - name: acesteps-service
        image: acesteps-service:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: BENTOML_HOME
          value: "/bentoml"
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: bentoml-storage
          mountPath: /bentoml
        - name: model-cache
          mountPath: /app/models
      volumes:
      - name: bentoml-storage
        emptyDir: {}
      - name: model-cache
        emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: acesteps-service
  labels:
    app: acesteps-service
spec:
  selector:
    app: acesteps-service
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acesteps-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - host: acesteps.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: acesteps-service
            port:
              number: 80
